name: posh
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.5
  google_sign_in: ^6.2.2
  provider: ^6.1.2
  http: ^1.2.2
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.17
  geolocator: ^13.0.2
  url_launcher: ^6.3.1 
  intl: ^0.20.1
  audioplayers: ^6.1.0
  permission_handler: ^11.3.1
  camera: ^0.11.1
  record: ^5.2.0
  audio_session: ^0.1.23
  just_audio: ^0.9.43
  flutter_background_service: ^5.1.0
  shimmer: ^3.0.0
    
dev_dependencies:
  flutter_test: 
    sdk: flutter

  flutter_lints: ^5.0.0
 
flutter:
  uses-material-design: true

  assets:  
    - assets/img/  
